version: '2'
services:
  web:
    image: airflow
    container_name: web
    command: bash -c "sleep 15;airflow initdb;airflow webserver"
    environment:
      - AIRFLOW_HOME=/opt/airflow
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/airflow
    depends_on:
      - mysql
      - redis
  scheduler:
    image: airflow
    container_name: scheduler
    command: bash -c "sleep 30;airflow scheduler"
    environment:
      - AIRFLOW_HOME=/opt/airflow
    volumes:
      - .:/opt/airflow
  worker:
    image: airflow
    command: bash -c "C_FORCE_ROOT=True airflow worker"
    environment:
      - AIRFLOW_HOME=/opt/airflow
    ports:
      - "5555"
    volumes:
      - .:/opt/airflow
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=airflow
    ports:
      - "3306:3306"
